language: python
python:
  - '3.6'
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels dranew
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda install -c olcbioinformatics cowbat
  
script:
  - pytest tests/test_imports.py -s -vv
  - pytest tests/test_pipeline.py -s -vv
