# packages in environment at /home/adamkoziol/miniconda3/envs/cowbat:
#
anaconda-client           1.6.14                   py35_0  
asn1crypto                0.24.0                   py35_0    conda-forge
attrs                     17.4.0                    <pip>
bbmap                     37.99                         0    bioconda
bcftools                  1.8                           1    bioconda
bcl2fastq                 2.19.0                        1    dranew
bedtools                  2.27.1                        1    bioconda
biopython                 1.71                      <pip>
blas                      1.0                         mkl    conda-forge
blast                     2.2.31                        1    bioconda
blosc                     1.14.3               hdbcaa40_0  
boost                     1.65.1                   py35_4  
boost-cpp                 1.65.1               h14c3975_4  
boost_lib                 1.54.0                        1    dranew
bowtie2                   2.3.4.1          py35pl5.22.0_0    bioconda
bzip2                     1.0.6                h9a117a8_4  
ca-certificates           2018.03.07                    0  
cairo                     1.14.10                       0    conda-forge
capnproto                 0.6.1                         0    conda-forge
certifi                   2018.4.16                py35_0    conda-forge
cffi                      1.11.5           py35h9745a5d_0  
chardet                   3.0.4            py35hb6e9ddf_1  
clark                     1.2.5                         0    bioconda
click                     6.7              py35h353a69f_0  
clyent                    1.2.2            py35h491ffcb_1  
confindr                  0.2.5                     <pip>
cryptography              2.2.2            py35h14c3975_0  
curl                      7.59.0               h84994c4_0  
cython                    0.28.2           py35h14c3975_0  
dbus                      1.11.0                        0    conda-forge
decorator                 4.3.0                    py35_0  
docopt                    0.6.2                     <pip>
expat                     2.2.5                he0dffb1_0  
fastqc                    0.11.7               pl5.22.0_2    bioconda
fastx-toolkit             0.0.14               pl5.22.0_1    biobuilds
fastx_toolkit             0.0.14               pl5.22.0_6    bioconda
fontconfig                2.12.6               h49f89f6_0  
freetype                  2.8.1                         0    conda-forge
GenomeQAML                0.0.11                    <pip>
gettext                   0.19.8.1             hd7bead4_3  
giflib                    5.1.4                h26a3ec6_1  
glib                      2.55.0                        0    conda-forge
gmp                       6.1.2                h6c8ec71_1  
gnuplot                   5.2.2                hfb11a44_0    conda-forge
gnutls                    3.5.17                        0    conda-forge
graphite2                 1.3.11               hf63cedd_1  
gsl                       2.2.1                h0c605f7_3  
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
harfbuzz                  1.7.6                         0    conda-forge
hdf5                      1.10.1               h9caa474_1  
icu                       58.2                 h9c2bf20_1  
idna                      2.6              py35h8605a33_1  
intel-openmp              2018.0.0                      8  
interop                   1.1.4                     <pip>
ipython_genutils          0.2.0            py35hc9e07d0_0  
jellyfish                 2.2.6                         0    bioconda
Jinja2                    2.10                      <pip>
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0            py35h4395190_0  
jupyter_core              4.4.0            py35ha89e94b_0  
kmc                       3.0.1                noasmlib_2    bioconda
krb5                      1.14.2               hcdc1b81_6  
libboost                  1.65.1               habcd387_4  
libcurl                   7.59.0               h1ad7b7a_0  
libdeflate                0.8                           0    bioconda
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                hdf63c60_3  
libgd                     2.2.5                         3    conda-forge
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libgtextutils             0.7                           3    bioconda
libiconv                  1.15                 h63c8f33_5  
libidn11                  1.33                          0    conda-forge
libopenblas               0.2.20               h9ac9557_4  
libpng                    1.6.34               hb9fc6fc_0  
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                he85c1e1_1  
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                hf84eae3_0  
livereload                2.5.1                     <pip>
lzo                       2.10                 h49e0be7_2  
mafft                     7.313                         0    bioconda
Markdown                  2.6.11                    <pip>
MarkupSafe                1.0                       <pip>
mash                      2.0                    gsl2.2_2    bioconda
mkdocs                    0.17.2                    <pip>
mkl                       2018.0.2                      1  
mkl_fft                   1.0.1            py35h3010b51_0  
mkl_random                1.0.1            py35h629b387_0  
nbformat                  4.4.0            py35h12e6e07_0  
ncurses                   5.9                          10    conda-forge
nettle                    3.3                           0    conda-forge
nose                      1.3.7            py35hdc64897_2  
numexpr                   2.6.5            py35h7bf3b9c_0  
numpy                     1.14.3           py35h14a74c5_0    anaconda
numpy-base                1.14.3           py35hdbf6ddf_0  
OLCTools                  0.3.89                    <pip>
openblas                  0.2.20                        4    conda-forge
openblas-devel            0.2.20                        4  
openjdk                   8.0.152              h46b5887_1  
openssl                   1.0.2o               h20670df_0  
pandas                    0.22.0           py35hf484d3e_0  
pango                     1.40.11              h8191d47_0  
pcre                      8.42                 h439df22_0  
perl                      5.22.0.1                      0    conda-forge
perl-app-cpanminus        1.7043               pl5.22.0_0    bioconda
perl-gd                   2.56                 pl5.22.0_6    bioconda
perl-gdgraph              1.49                 pl5.22.0_3    bioconda
perl-gdgraph-histogram    1.1                  pl5.22.0_1    bioconda
perl-gdtextutil           0.86                 pl5.22.0_3    bioconda
perl-perlio-gzip          0.19                 pl5.22.0_2    bioconda
pilon                     1.22                     py35_0    bioconda
pip                       10.0.1                   py35_0  
pip                       10.0.1                    <pip>
pixman                    0.34.0               hceecf20_3  
plasmidextractor          0.2.3                     <pip>
pluggy                    0.6.0                     <pip>
prodigal                  2.6.3                         0    biobuilds
psutil                    5.4.5            py35h14c3975_0  
py                        1.5.2                     <pip>
py-boost                  1.65.1           py35hf484d3e_4  
pycparser                 2.18             py35h61b3040_1  
pycurl                    7.43.0.1         py35hb7f436b_0  
pyopenssl                 17.5.0           py35h4f8b8c8_0  
pysam                     0.13                      <pip>
pysocks                   1.6.8                    py35_0  
pytables                  3.4.3            py35h02b9ad4_0  
pytest                    3.4.1                     <pip>
python                    3.5.4               h56e0582_23  
python-dateutil           2.7.2                    py35_0  
pytz                      2018.4                   py35_0  
pyyaml                    3.12             py35h46ef4ae_1  
qt                        5.6.2                         7    conda-forge
qualimap                  2.2.2a                        1    bioconda
rauth                     0.7.3                      py_0    conda-forge
readline                  7.0                  hb321a52_4  
requests                  2.18.4           py35hb9e6ad1_1  
samtools                  1.8                           3    bioconda
scikit-learn              0.19.1                    <pip>
scipy                     1.0.0                     <pip>
seqtk                     1.2                           1    bioconda
setuptools                39.1.0                   py35_0    conda-forge
sipprverse                0.0.69                    <pip>
sistr_cmd                 1.0.2                    py35_0    bioconda
six                       1.11.0           py35h423b573_1  
skesa                     2.1                           0    bioconda
sklearn                   0.0                       <pip>
snappy                    1.1.7                hbae5bb6_3  
spades                    3.11.1          py35_zlib1.2.11_1    bioconda
sqlite                    3.20.1                        2    conda-forge
tablet                    1.17.08.17                    1    bioconda
tbb                       2018.0.2             hf484d3e_0  
tk                        8.6.7                hc745277_3  
tornado                   4.5.3                     <pip>
traitlets                 4.3.2            py35ha522a97_0  
urllib3                   1.22             py35h2ab6e29_0  
wheel                     0.31.0                   py35_0    conda-forge
XlsxWriter                1.0.2                     <pip>
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                h5e939de_4  
yaml                      0.1.7                had09818_2  
yarg                      0.1.9                     <pip>
zlib                      1.2.11               ha838bed_2  
