site_name: COWBAT Documentation
theme: readthedocs
repo_url: 'https://github.com/OLC-Bioinformatics/COWBAT'

pages:
    - Home: 'index.md'
    - Overview: 'overview.md'
    - Installation: 'installation.md'
    - Tutorial: 'tutorial.md'
    - Tests: 'tests.md'
    - Typing: 'typing.md'
