#!/usr/bin/env python
import bz2
from Queue import Queue
from glob import glob
from threading import Thread

from accessoryFunctions import *

__author__ = 'adamkoziol'


class Compress(object):

    def compressthreads(self):
        """Compresses large files created by the pipeline"""
        import re
        printtime('Compressing large files', self. start)
        compressfile = []
        for sample in self.metadata:
            if sample.general.bestassemblyfile != 'NA':
                for key, value in sample.general.datastore.items():
                    if type(value) is list:
                        for item in value:
                            if re.search(".fastq$", item):
                                compressfile.append(item)
        for i in range(len(compressfile)):
            # Send the threads to makeblastdb
            threads = Thread(target=self.compress, args=())
            # Set the daemon to true - something to do with thread management
            threads.setDaemon(True)
            # Start the threading
            threads.start()
            # Make blast databases for MLST files (if necessary)
        for compress in compressfile:
            self.compressqueue.put(compress)
        self.compressqueue.join()  # wait on the dqueue until everything has been processed
        self.remove()

    def compress(self):
        while True:
            compressfile = self.compressqueue.get()
            if '.bz2' not in compressfile:
                if not os.path.isfile('{}.bz2'.format(compressfile)):
                    output = bz2.BZ2File('{}.bz2'.format(compressfile), 'wb')
                    with open(compressfile, 'rb') as inputfile:
                        for inputdata in inputfile:
                            output.write(inputdata)
                    output.close()
                if os.path.isfile('{}.bz2'.format(compressfile)):
                    try:
                        os.remove(compressfile)
                    except (OSError, IOError):
                        pass
            self.compressqueue.task_done()

    def remove(self):
        """Removes unnecessary temporary files generated by the pipeline"""
        import shutil
        printtime('Removing temporary files', self.start)
        removefile = []
        for sample in self.metadata:
            if sample.general.bestassemblyfile != 'NA':
                removefile.append(glob('{}/K*/'.format(sample.general.spadesoutput)))
                removefile.append('{}/misc/'.format(sample.general.spadesoutput))
                removefile.append('{}/tmp/'.format(sample.general.spadesoutput))
        # Clear out the folders
        for folder in removefile:
            try:
                shutil.rmtree(folder)
            except (OSError, TypeError):
                pass

    def __init__(self, inputobject):
        self.metadata = inputobject.runmetadata.samples
        self.start = inputobject.starttime
        self.compressqueue = Queue()
        self.compressthreads()
