# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_py_interop_summary')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_py_interop_summary')
    _py_interop_summary = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_py_interop_summary', [dirname(__file__)])
        except ImportError:
            import _py_interop_summary
            return _py_interop_summary
        try:
            _mod = imp.load_module('_py_interop_summary', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _py_interop_summary = swig_import_helper()
    del swig_import_helper
else:
    import _py_interop_summary
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _py_interop_summary.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _py_interop_summary.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _py_interop_summary.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _py_interop_summary.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _py_interop_summary.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _py_interop_summary.SwigPyIterator_equal(self, x)

    def copy(self):
        return _py_interop_summary.SwigPyIterator_copy(self)

    def next(self):
        return _py_interop_summary.SwigPyIterator_next(self)

    def __next__(self):
        return _py_interop_summary.SwigPyIterator___next__(self)

    def previous(self):
        return _py_interop_summary.SwigPyIterator_previous(self)

    def advance(self, n):
        return _py_interop_summary.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _py_interop_summary.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _py_interop_summary.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _py_interop_summary.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _py_interop_summary.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _py_interop_summary.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _py_interop_summary.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _py_interop_summary.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

import interop.py_interop_run
import interop.py_interop_metrics
import interop.py_interop_run_metrics
import interop.py_interop_comm
class cycle_state_summary(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, cycle_state_summary, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, cycle_state_summary, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _py_interop_summary.new_cycle_state_summary()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def empty(self):
        return _py_interop_summary.cycle_state_summary_empty(self)

    def extracted_cycle_range(self, *args):
        return _py_interop_summary.cycle_state_summary_extracted_cycle_range(self, *args)

    def called_cycle_range(self, *args):
        return _py_interop_summary.cycle_state_summary_called_cycle_range(self, *args)

    def qscored_cycle_range(self, *args):
        return _py_interop_summary.cycle_state_summary_qscored_cycle_range(self, *args)

    def error_cycle_range(self, *args):
        return _py_interop_summary.cycle_state_summary_error_cycle_range(self, *args)
    __swig_destroy__ = _py_interop_summary.delete_cycle_state_summary
    __del__ = lambda self: None
cycle_state_summary_swigregister = _py_interop_summary.cycle_state_summary_swigregister
cycle_state_summary_swigregister(cycle_state_summary)

class stat_summary(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, stat_summary, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, stat_summary, name)
    __repr__ = _swig_repr

    def __init__(self, arg2):
        this = _py_interop_summary.new_stat_summary(arg2)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def percent_gt_q30(self, *args):
        return _py_interop_summary.stat_summary_percent_gt_q30(self, *args)

    def yield_g(self, *args):
        return _py_interop_summary.stat_summary_yield_g(self, *args)

    def projected_yield_g(self, *args):
        return _py_interop_summary.stat_summary_projected_yield_g(self, *args)

    def reads(self, *args):
        return _py_interop_summary.stat_summary_reads(self, *args)

    def reads_pf(self, *args):
        return _py_interop_summary.stat_summary_reads_pf(self, *args)

    def density(self, *args):
        return _py_interop_summary.stat_summary_density(self, *args)

    def density_pf(self, *args):
        return _py_interop_summary.stat_summary_density_pf(self, *args)

    def cluster_count(self, *args):
        return _py_interop_summary.stat_summary_cluster_count(self, *args)

    def cluster_count_pf(self, *args):
        return _py_interop_summary.stat_summary_cluster_count_pf(self, *args)

    def percent_pf(self, *args):
        return _py_interop_summary.stat_summary_percent_pf(self, *args)

    def phasing(self, *args):
        return _py_interop_summary.stat_summary_phasing(self, *args)

    def prephasing(self, *args):
        return _py_interop_summary.stat_summary_prephasing(self, *args)

    def percent_aligned(self, *args):
        return _py_interop_summary.stat_summary_percent_aligned(self, *args)

    def error_rate(self, *args):
        return _py_interop_summary.stat_summary_error_rate(self, *args)

    def error_rate_35(self, *args):
        return _py_interop_summary.stat_summary_error_rate_35(self, *args)

    def error_rate_50(self, *args):
        return _py_interop_summary.stat_summary_error_rate_50(self, *args)

    def error_rate_75(self, *args):
        return _py_interop_summary.stat_summary_error_rate_75(self, *args)

    def error_rate_100(self, *args):
        return _py_interop_summary.stat_summary_error_rate_100(self, *args)

    def first_cycle_intensity(self, *args):
        return _py_interop_summary.stat_summary_first_cycle_intensity(self, *args)

    def phasing_slope(self, *args):
        return _py_interop_summary.stat_summary_phasing_slope(self, *args)

    def phasing_offset(self, *args):
        return _py_interop_summary.stat_summary_phasing_offset(self, *args)

    def prephasing_slope(self, *args):
        return _py_interop_summary.stat_summary_prephasing_slope(self, *args)

    def prephasing_offset(self, *args):
        return _py_interop_summary.stat_summary_prephasing_offset(self, *args)

    def resize_stat(self, arg2):
        return _py_interop_summary.stat_summary_resize_stat(self, arg2)
    __swig_destroy__ = _py_interop_summary.delete_stat_summary
    __del__ = lambda self: None
stat_summary_swigregister = _py_interop_summary.stat_summary_swigregister
stat_summary_swigregister(stat_summary)

class surface_summary(stat_summary):
    __swig_setmethods__ = {}
    for _s in [stat_summary]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, surface_summary, name, value)
    __swig_getmethods__ = {}
    for _s in [stat_summary]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, surface_summary, name)
    __repr__ = _swig_repr

    def __init__(self, surface=0, channel_count=0):
        this = _py_interop_summary.new_surface_summary(surface, channel_count)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def surface(self, *args):
        return _py_interop_summary.surface_summary_surface(self, *args)

    def tile_count(self, *args):
        return _py_interop_summary.surface_summary_tile_count(self, *args)
    __swig_destroy__ = _py_interop_summary.delete_surface_summary
    __del__ = lambda self: None
surface_summary_swigregister = _py_interop_summary.surface_summary_swigregister
surface_summary_swigregister(surface_summary)

class metric_summary(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, metric_summary, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, metric_summary, name)
    __repr__ = _swig_repr

    def __init__(self, arg2):
        this = _py_interop_summary.new_metric_summary(arg2)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def first_cycle_intensity(self, *args):
        return _py_interop_summary.metric_summary_first_cycle_intensity(self, *args)

    def error_rate(self, *args):
        return _py_interop_summary.metric_summary_error_rate(self, *args)

    def percent_aligned(self, *args):
        return _py_interop_summary.metric_summary_percent_aligned(self, *args)

    def percent_gt_q30(self, *args):
        return _py_interop_summary.metric_summary_percent_gt_q30(self, *args)

    def yield_g(self, *args):
        return _py_interop_summary.metric_summary_yield_g(self, *args)

    def projected_yield_g(self, *args):
        return _py_interop_summary.metric_summary_projected_yield_g(self, *args)

    def resize(self, arg2):
        return _py_interop_summary.metric_summary_resize(self, arg2)
    __swig_destroy__ = _py_interop_summary.delete_metric_summary
    __del__ = lambda self: None
metric_summary_swigregister = _py_interop_summary.metric_summary_swigregister
metric_summary_swigregister(metric_summary)

class lane_summary(stat_summary):
    __swig_setmethods__ = {}
    for _s in [stat_summary]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, lane_summary, name, value)
    __swig_getmethods__ = {}
    for _s in [stat_summary]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, lane_summary, name)
    __repr__ = _swig_repr

    def __init__(self, lane=0, channel_count=0):
        this = _py_interop_summary.new_lane_summary(lane, channel_count)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def at(self, n):
        return _py_interop_summary.lane_summary_at(self, n)

    def resize(self, n):
        return _py_interop_summary.lane_summary_resize(self, n)

    def cycle_state(self):
        return _py_interop_summary.lane_summary_cycle_state(self)

    def lane(self, *args):
        return _py_interop_summary.lane_summary_lane(self, *args)

    def tile_count(self, *args):
        return _py_interop_summary.lane_summary_tile_count(self, *args)

    def size(self):
        return _py_interop_summary.lane_summary_size(self)
    __swig_destroy__ = _py_interop_summary.delete_lane_summary
    __del__ = lambda self: None
lane_summary_swigregister = _py_interop_summary.lane_summary_swigregister
lane_summary_swigregister(lane_summary)

class metric_stat(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, metric_stat, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, metric_stat, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _py_interop_summary.new_metric_stat(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def clear(self):
        return _py_interop_summary.metric_stat_clear(self)

    def mean(self, *args):
        return _py_interop_summary.metric_stat_mean(self, *args)

    def stddev(self, *args):
        return _py_interop_summary.metric_stat_stddev(self, *args)

    def median(self, *args):
        return _py_interop_summary.metric_stat_median(self, *args)
    __swig_destroy__ = _py_interop_summary.delete_metric_stat
    __del__ = lambda self: None
metric_stat_swigregister = _py_interop_summary.metric_stat_swigregister
metric_stat_swigregister(metric_stat)

class read_summary(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, read_summary, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, read_summary, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _py_interop_summary.new_read_summary(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def at(self, n):
        return _py_interop_summary.read_summary_at(self, n)

    def resize(self, n):
        return _py_interop_summary.read_summary_resize(self, n)

    def read(self):
        return _py_interop_summary.read_summary_read(self)

    def summary(self, *args):
        return _py_interop_summary.read_summary_summary(self, *args)

    def size(self):
        return _py_interop_summary.read_summary_size(self)

    def lane_count(self):
        return _py_interop_summary.read_summary_lane_count(self)
    __swig_destroy__ = _py_interop_summary.delete_read_summary
    __del__ = lambda self: None
read_summary_swigregister = _py_interop_summary.read_summary_swigregister
read_summary_swigregister(read_summary)

class run_summary(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, run_summary, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, run_summary, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _py_interop_summary.new_run_summary(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def initialize(self, *args):
        return _py_interop_summary.run_summary_initialize(self, *args)

    def copy_reads(self, dst):
        return _py_interop_summary.run_summary_copy_reads(self, dst)

    def at(self, n):
        return _py_interop_summary.run_summary_at(self, n)

    def size(self):
        return _py_interop_summary.run_summary_size(self)

    def lane_count(self, *args):
        return _py_interop_summary.run_summary_lane_count(self, *args)

    def channel_count(self):
        return _py_interop_summary.run_summary_channel_count(self)

    def surface_count(self, *args):
        return _py_interop_summary.run_summary_surface_count(self, *args)

    def total_summary(self, *args):
        return _py_interop_summary.run_summary_total_summary(self, *args)

    def nonindex_summary(self, *args):
        return _py_interop_summary.run_summary_nonindex_summary(self, *args)

    def cycle_state(self):
        return _py_interop_summary.run_summary_cycle_state(self)

    def clear(self):
        return _py_interop_summary.run_summary_clear(self)
    __swig_destroy__ = _py_interop_summary.delete_run_summary
    __del__ = lambda self: None
run_summary_swigregister = _py_interop_summary.run_summary_swigregister
run_summary_swigregister(run_summary)

class surface_summary_vector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, surface_summary_vector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, surface_summary_vector, name)
    __repr__ = _swig_repr
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _py_interop_summary.surface_summary_vector___nonzero__(self)

    def __bool__(self):
        return _py_interop_summary.surface_summary_vector___bool__(self)

    def __len__(self):
        return _py_interop_summary.surface_summary_vector___len__(self)

    def __getslice__(self, i, j):
        return _py_interop_summary.surface_summary_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _py_interop_summary.surface_summary_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _py_interop_summary.surface_summary_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _py_interop_summary.surface_summary_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _py_interop_summary.surface_summary_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _py_interop_summary.surface_summary_vector___setitem__(self, *args)

    def pop(self):
        return _py_interop_summary.surface_summary_vector_pop(self)

    def append(self, x):
        return _py_interop_summary.surface_summary_vector_append(self, x)

    def empty(self):
        return _py_interop_summary.surface_summary_vector_empty(self)

    def size(self):
        return _py_interop_summary.surface_summary_vector_size(self)

    def swap(self, v):
        return _py_interop_summary.surface_summary_vector_swap(self, v)

    def rbegin(self):
        return _py_interop_summary.surface_summary_vector_rbegin(self)

    def rend(self):
        return _py_interop_summary.surface_summary_vector_rend(self)

    def clear(self):
        return _py_interop_summary.surface_summary_vector_clear(self)

    def get_allocator(self):
        return _py_interop_summary.surface_summary_vector_get_allocator(self)

    def pop_back(self):
        return _py_interop_summary.surface_summary_vector_pop_back(self)

    def erase(self, *args):
        return _py_interop_summary.surface_summary_vector_erase(self, *args)

    def __init__(self, *args):
        this = _py_interop_summary.new_surface_summary_vector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _py_interop_summary.surface_summary_vector_push_back(self, x)

    def front(self):
        return _py_interop_summary.surface_summary_vector_front(self)

    def back(self):
        return _py_interop_summary.surface_summary_vector_back(self)

    def assign(self, n, x):
        return _py_interop_summary.surface_summary_vector_assign(self, n, x)

    def resize(self, *args):
        return _py_interop_summary.surface_summary_vector_resize(self, *args)

    def insert(self, *args):
        return _py_interop_summary.surface_summary_vector_insert(self, *args)

    def reserve(self, n):
        return _py_interop_summary.surface_summary_vector_reserve(self, n)

    def capacity(self):
        return _py_interop_summary.surface_summary_vector_capacity(self)
    __swig_destroy__ = _py_interop_summary.delete_surface_summary_vector
    __del__ = lambda self: None
surface_summary_vector_swigregister = _py_interop_summary.surface_summary_vector_swigregister
surface_summary_vector_swigregister(surface_summary_vector)

class lane_summary_vector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, lane_summary_vector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, lane_summary_vector, name)
    __repr__ = _swig_repr
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _py_interop_summary.lane_summary_vector___nonzero__(self)

    def __bool__(self):
        return _py_interop_summary.lane_summary_vector___bool__(self)

    def __len__(self):
        return _py_interop_summary.lane_summary_vector___len__(self)

    def __getslice__(self, i, j):
        return _py_interop_summary.lane_summary_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _py_interop_summary.lane_summary_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _py_interop_summary.lane_summary_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _py_interop_summary.lane_summary_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _py_interop_summary.lane_summary_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _py_interop_summary.lane_summary_vector___setitem__(self, *args)

    def pop(self):
        return _py_interop_summary.lane_summary_vector_pop(self)

    def append(self, x):
        return _py_interop_summary.lane_summary_vector_append(self, x)

    def empty(self):
        return _py_interop_summary.lane_summary_vector_empty(self)

    def size(self):
        return _py_interop_summary.lane_summary_vector_size(self)

    def swap(self, v):
        return _py_interop_summary.lane_summary_vector_swap(self, v)

    def rbegin(self):
        return _py_interop_summary.lane_summary_vector_rbegin(self)

    def rend(self):
        return _py_interop_summary.lane_summary_vector_rend(self)

    def clear(self):
        return _py_interop_summary.lane_summary_vector_clear(self)

    def get_allocator(self):
        return _py_interop_summary.lane_summary_vector_get_allocator(self)

    def pop_back(self):
        return _py_interop_summary.lane_summary_vector_pop_back(self)

    def erase(self, *args):
        return _py_interop_summary.lane_summary_vector_erase(self, *args)

    def __init__(self, *args):
        this = _py_interop_summary.new_lane_summary_vector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _py_interop_summary.lane_summary_vector_push_back(self, x)

    def front(self):
        return _py_interop_summary.lane_summary_vector_front(self)

    def back(self):
        return _py_interop_summary.lane_summary_vector_back(self)

    def assign(self, n, x):
        return _py_interop_summary.lane_summary_vector_assign(self, n, x)

    def resize(self, *args):
        return _py_interop_summary.lane_summary_vector_resize(self, *args)

    def insert(self, *args):
        return _py_interop_summary.lane_summary_vector_insert(self, *args)

    def reserve(self, n):
        return _py_interop_summary.lane_summary_vector_reserve(self, n)

    def capacity(self):
        return _py_interop_summary.lane_summary_vector_capacity(self)
    __swig_destroy__ = _py_interop_summary.delete_lane_summary_vector
    __del__ = lambda self: None
lane_summary_vector_swigregister = _py_interop_summary.lane_summary_vector_swigregister
lane_summary_vector_swigregister(lane_summary_vector)

class read_summary_vector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, read_summary_vector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, read_summary_vector, name)
    __repr__ = _swig_repr
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _py_interop_summary.read_summary_vector___nonzero__(self)

    def __bool__(self):
        return _py_interop_summary.read_summary_vector___bool__(self)

    def __len__(self):
        return _py_interop_summary.read_summary_vector___len__(self)

    def __getslice__(self, i, j):
        return _py_interop_summary.read_summary_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _py_interop_summary.read_summary_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _py_interop_summary.read_summary_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _py_interop_summary.read_summary_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _py_interop_summary.read_summary_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _py_interop_summary.read_summary_vector___setitem__(self, *args)

    def pop(self):
        return _py_interop_summary.read_summary_vector_pop(self)

    def append(self, x):
        return _py_interop_summary.read_summary_vector_append(self, x)

    def empty(self):
        return _py_interop_summary.read_summary_vector_empty(self)

    def size(self):
        return _py_interop_summary.read_summary_vector_size(self)

    def swap(self, v):
        return _py_interop_summary.read_summary_vector_swap(self, v)

    def rbegin(self):
        return _py_interop_summary.read_summary_vector_rbegin(self)

    def rend(self):
        return _py_interop_summary.read_summary_vector_rend(self)

    def clear(self):
        return _py_interop_summary.read_summary_vector_clear(self)

    def get_allocator(self):
        return _py_interop_summary.read_summary_vector_get_allocator(self)

    def pop_back(self):
        return _py_interop_summary.read_summary_vector_pop_back(self)

    def erase(self, *args):
        return _py_interop_summary.read_summary_vector_erase(self, *args)

    def __init__(self, *args):
        this = _py_interop_summary.new_read_summary_vector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _py_interop_summary.read_summary_vector_push_back(self, x)

    def front(self):
        return _py_interop_summary.read_summary_vector_front(self)

    def back(self):
        return _py_interop_summary.read_summary_vector_back(self)

    def assign(self, n, x):
        return _py_interop_summary.read_summary_vector_assign(self, n, x)

    def resize(self, *args):
        return _py_interop_summary.read_summary_vector_resize(self, *args)

    def insert(self, *args):
        return _py_interop_summary.read_summary_vector_insert(self, *args)

    def reserve(self, n):
        return _py_interop_summary.read_summary_vector_reserve(self, n)

    def capacity(self):
        return _py_interop_summary.read_summary_vector_capacity(self)
    __swig_destroy__ = _py_interop_summary.delete_read_summary_vector
    __del__ = lambda self: None
read_summary_vector_swigregister = _py_interop_summary.read_summary_vector_swigregister
read_summary_vector_swigregister(read_summary_vector)


def summarize_run_metrics(metrics, summary, skip_median=False, trim=True):
    return _py_interop_summary.summarize_run_metrics(metrics, summary, skip_median, trim)
summarize_run_metrics = _py_interop_summary.summarize_run_metrics
class index_count_summary(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, index_count_summary, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, index_count_summary, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _py_interop_summary.new_index_count_summary(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def index1(self):
        return _py_interop_summary.index_count_summary_index1(self)

    def index2(self):
        return _py_interop_summary.index_count_summary_index2(self)

    def fraction_mapped(self):
        return _py_interop_summary.index_count_summary_fraction_mapped(self)

    def cluster_count(self):
        return _py_interop_summary.index_count_summary_cluster_count(self)

    def sample_id(self):
        return _py_interop_summary.index_count_summary_sample_id(self)

    def project_name(self):
        return _py_interop_summary.index_count_summary_project_name(self)

    def id(self, *args):
        return _py_interop_summary.index_count_summary_id(self, *args)

    def add(self, cluster_count):
        return _py_interop_summary.index_count_summary_add(self, cluster_count)

    def update_fraction_mapped(self, total_pf_cluster_count):
        return _py_interop_summary.index_count_summary_update_fraction_mapped(self, total_pf_cluster_count)

    def __lt__(self, rhs):
        return _py_interop_summary.index_count_summary___lt__(self, rhs)
    __swig_destroy__ = _py_interop_summary.delete_index_count_summary
    __del__ = lambda self: None
index_count_summary_swigregister = _py_interop_summary.index_count_summary_swigregister
index_count_summary_swigregister(index_count_summary)

class index_lane_summary(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, index_lane_summary, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, index_lane_summary, name)
    __repr__ = _swig_repr

    def __init__(self, total_reads=0, total_pf_reads=0, total_fraction_mapped_reads=0, mapped_reads_cv=0, min_mapped_reads=0, max_mapped_reads=0):
        this = _py_interop_summary.new_index_lane_summary(total_reads, total_pf_reads, total_fraction_mapped_reads, mapped_reads_cv, min_mapped_reads, max_mapped_reads)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def resize(self, n):
        return _py_interop_summary.index_lane_summary_resize(self, n)

    def reserve(self, n):
        return _py_interop_summary.index_lane_summary_reserve(self, n)

    def push_back(self, count_summary):
        return _py_interop_summary.index_lane_summary_push_back(self, count_summary)

    def size(self):
        return _py_interop_summary.index_lane_summary_size(self)

    def at(self, n):
        return _py_interop_summary.index_lane_summary_at(self, n)

    def total_reads(self):
        return _py_interop_summary.index_lane_summary_total_reads(self)

    def total_pf_reads(self):
        return _py_interop_summary.index_lane_summary_total_pf_reads(self)

    def total_fraction_mapped_reads(self):
        return _py_interop_summary.index_lane_summary_total_fraction_mapped_reads(self)

    def mapped_reads_cv(self):
        return _py_interop_summary.index_lane_summary_mapped_reads_cv(self)

    def min_mapped_reads(self):
        return _py_interop_summary.index_lane_summary_min_mapped_reads(self)

    def max_mapped_reads(self):
        return _py_interop_summary.index_lane_summary_max_mapped_reads(self)

    def sort(self):
        return _py_interop_summary.index_lane_summary_sort(self)

    def set(self, total_mapped_reads, pf_cluster_count_total, cluster_count_total, min_fraction_mapped, max_fraction_mapped, cv_fraction_mapped):
        return _py_interop_summary.index_lane_summary_set(self, total_mapped_reads, pf_cluster_count_total, cluster_count_total, min_fraction_mapped, max_fraction_mapped, cv_fraction_mapped)

    def clear(self):
        return _py_interop_summary.index_lane_summary_clear(self)
    __swig_destroy__ = _py_interop_summary.delete_index_lane_summary
    __del__ = lambda self: None
index_lane_summary_swigregister = _py_interop_summary.index_lane_summary_swigregister
index_lane_summary_swigregister(index_lane_summary)

class index_flowcell_summary(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, index_flowcell_summary, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, index_flowcell_summary, name)
    __repr__ = _swig_repr

    def __init__(self, n=0):
        this = _py_interop_summary.new_index_flowcell_summary(n)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def at(self, n):
        return _py_interop_summary.index_flowcell_summary_at(self, n)

    def size(self):
        return _py_interop_summary.index_flowcell_summary_size(self)

    def resize(self, n):
        return _py_interop_summary.index_flowcell_summary_resize(self, n)

    def sort(self):
        return _py_interop_summary.index_flowcell_summary_sort(self)

    def clear(self):
        return _py_interop_summary.index_flowcell_summary_clear(self)
    __swig_destroy__ = _py_interop_summary.delete_index_flowcell_summary
    __del__ = lambda self: None
index_flowcell_summary_swigregister = _py_interop_summary.index_flowcell_summary_swigregister
index_flowcell_summary_swigregister(index_flowcell_summary)

class index_count_summary_vector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, index_count_summary_vector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, index_count_summary_vector, name)
    __repr__ = _swig_repr
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _py_interop_summary.index_count_summary_vector___nonzero__(self)

    def __bool__(self):
        return _py_interop_summary.index_count_summary_vector___bool__(self)

    def __len__(self):
        return _py_interop_summary.index_count_summary_vector___len__(self)

    def __getslice__(self, i, j):
        return _py_interop_summary.index_count_summary_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _py_interop_summary.index_count_summary_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _py_interop_summary.index_count_summary_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _py_interop_summary.index_count_summary_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _py_interop_summary.index_count_summary_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _py_interop_summary.index_count_summary_vector___setitem__(self, *args)

    def pop(self):
        return _py_interop_summary.index_count_summary_vector_pop(self)

    def append(self, x):
        return _py_interop_summary.index_count_summary_vector_append(self, x)

    def empty(self):
        return _py_interop_summary.index_count_summary_vector_empty(self)

    def size(self):
        return _py_interop_summary.index_count_summary_vector_size(self)

    def swap(self, v):
        return _py_interop_summary.index_count_summary_vector_swap(self, v)

    def rbegin(self):
        return _py_interop_summary.index_count_summary_vector_rbegin(self)

    def rend(self):
        return _py_interop_summary.index_count_summary_vector_rend(self)

    def clear(self):
        return _py_interop_summary.index_count_summary_vector_clear(self)

    def get_allocator(self):
        return _py_interop_summary.index_count_summary_vector_get_allocator(self)

    def pop_back(self):
        return _py_interop_summary.index_count_summary_vector_pop_back(self)

    def erase(self, *args):
        return _py_interop_summary.index_count_summary_vector_erase(self, *args)

    def __init__(self, *args):
        this = _py_interop_summary.new_index_count_summary_vector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _py_interop_summary.index_count_summary_vector_push_back(self, x)

    def front(self):
        return _py_interop_summary.index_count_summary_vector_front(self)

    def back(self):
        return _py_interop_summary.index_count_summary_vector_back(self)

    def assign(self, n, x):
        return _py_interop_summary.index_count_summary_vector_assign(self, n, x)

    def resize(self, *args):
        return _py_interop_summary.index_count_summary_vector_resize(self, *args)

    def insert(self, *args):
        return _py_interop_summary.index_count_summary_vector_insert(self, *args)

    def reserve(self, n):
        return _py_interop_summary.index_count_summary_vector_reserve(self, n)

    def capacity(self):
        return _py_interop_summary.index_count_summary_vector_capacity(self)
    __swig_destroy__ = _py_interop_summary.delete_index_count_summary_vector
    __del__ = lambda self: None
index_count_summary_vector_swigregister = _py_interop_summary.index_count_summary_vector_swigregister
index_count_summary_vector_swigregister(index_count_summary_vector)

class index_lane_summary_vector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, index_lane_summary_vector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, index_lane_summary_vector, name)
    __repr__ = _swig_repr
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _py_interop_summary.index_lane_summary_vector___nonzero__(self)

    def __bool__(self):
        return _py_interop_summary.index_lane_summary_vector___bool__(self)

    def __len__(self):
        return _py_interop_summary.index_lane_summary_vector___len__(self)

    def __getslice__(self, i, j):
        return _py_interop_summary.index_lane_summary_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _py_interop_summary.index_lane_summary_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _py_interop_summary.index_lane_summary_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _py_interop_summary.index_lane_summary_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _py_interop_summary.index_lane_summary_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _py_interop_summary.index_lane_summary_vector___setitem__(self, *args)

    def pop(self):
        return _py_interop_summary.index_lane_summary_vector_pop(self)

    def append(self, x):
        return _py_interop_summary.index_lane_summary_vector_append(self, x)

    def empty(self):
        return _py_interop_summary.index_lane_summary_vector_empty(self)

    def size(self):
        return _py_interop_summary.index_lane_summary_vector_size(self)

    def swap(self, v):
        return _py_interop_summary.index_lane_summary_vector_swap(self, v)

    def rbegin(self):
        return _py_interop_summary.index_lane_summary_vector_rbegin(self)

    def rend(self):
        return _py_interop_summary.index_lane_summary_vector_rend(self)

    def clear(self):
        return _py_interop_summary.index_lane_summary_vector_clear(self)

    def get_allocator(self):
        return _py_interop_summary.index_lane_summary_vector_get_allocator(self)

    def pop_back(self):
        return _py_interop_summary.index_lane_summary_vector_pop_back(self)

    def erase(self, *args):
        return _py_interop_summary.index_lane_summary_vector_erase(self, *args)

    def __init__(self, *args):
        this = _py_interop_summary.new_index_lane_summary_vector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _py_interop_summary.index_lane_summary_vector_push_back(self, x)

    def front(self):
        return _py_interop_summary.index_lane_summary_vector_front(self)

    def back(self):
        return _py_interop_summary.index_lane_summary_vector_back(self)

    def assign(self, n, x):
        return _py_interop_summary.index_lane_summary_vector_assign(self, n, x)

    def resize(self, *args):
        return _py_interop_summary.index_lane_summary_vector_resize(self, *args)

    def insert(self, *args):
        return _py_interop_summary.index_lane_summary_vector_insert(self, *args)

    def reserve(self, n):
        return _py_interop_summary.index_lane_summary_vector_reserve(self, n)

    def capacity(self):
        return _py_interop_summary.index_lane_summary_vector_capacity(self)
    __swig_destroy__ = _py_interop_summary.delete_index_lane_summary_vector
    __del__ = lambda self: None
index_lane_summary_vector_swigregister = _py_interop_summary.index_lane_summary_vector_swigregister
index_lane_summary_vector_swigregister(index_lane_summary_vector)


def summarize_index_metrics(*args):
    return _py_interop_summary.summarize_index_metrics(*args)
summarize_index_metrics = _py_interop_summary.summarize_index_metrics
# This file is compatible with both classic and new-style classes.


